---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Ollama
  ansible.builtin.systemd_service:
    name: ollama
    enabled: true
    state: restarted

- name: Restart Local AI Assistant
  ansible.builtin.systemd_service:
    name: local-ai-assistant
    enabled: true
    state: restarted
