#!/usr/bin/env bash
set -Eeuo pipefail

if [[ $# -lt 1 || $# -gt 2 || ! "$1" =~ ^(dev|prod)$ ]]; then
  echo "Usage: $0 dev|prod [operator-config-file]" >&2
  exit 2
fi

environment=$1
operator_file=${2:-.github/deployment-config/operator.env}
deployment_file=".github/deployment-config/${environment}.env"

if [[ ! -f "$operator_file" ]]; then
  echo "Missing $operator_file. Copy .github/deployment-config/operator.env.example first." >&2
  exit 2
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI (gh) is required. Install it, then run: gh auth login" >&2
  exit 2
fi

if ! gh auth status --hostname github.com >/dev/null 2>&1; then
  echo "Authenticate GitHub CLI first: gh auth login" >&2
  exit 2
fi

read_setting() {
  local key=$1
  local value
  value=$(awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$operator_file")
  printf '%s' "$value"
}

require_setting() {
  local key=$1
  local value
  value=$(read_setting "$key")
  if [[ -z "$value" || "$value" == YOUR_* || "$value" == "operator@example.com" ]]; then
    read -r -p "Enter $key: " value </dev/tty
    if [[ -z "$value" ]]; then
      echo "$key is required" >&2
      exit 2
    fi
    update_setting "$key" "$value"
  fi
  printf '%s' "$value"
}

update_setting() {
  local key=$1
  local value=$2
  local temporary_file
  temporary_file=$(mktemp)
  awk -F= -v key="$key" -v value="$value" '
    $1 == key { print key "=" value; found = 1; next }
    { print }
    END { if (!found) print key "=" value }
  ' "$operator_file" >"$temporary_file"
  mv "$temporary_file" "$operator_file"
}

bootstrap_output() {
  terraform -chdir=terraform/bootstrap output -raw "$1"
}

github_owner=$(require_setting GITHUB_OWNER)
github_repository=$(require_setting GITHUB_REPOSITORY)
alarm_email=$(require_setting ALARM_EMAIL)
repository="${github_owner}/${github_repository}"

role_arn=$(bootstrap_output github_deploy_role_arn)
ecr_repository_url=$(bootstrap_output ecr_repository_url)
state_bucket=$(bootstrap_output state_bucket_name)
state_kms_key_id=$(bootstrap_output state_kms_key_arn)

enable_duckdns=$(read_setting "${environment^^}_ENABLE_DUCKDNS")
enable_letsencrypt=$(read_setting "${environment^^}_ENABLE_LETSENCRYPT")

if [[ "$enable_duckdns" != "true" && "$enable_duckdns" != "false" ]]; then
  echo "${environment^^}_ENABLE_DUCKDNS must be true or false" >&2
  exit 2
fi
if [[ "$enable_letsencrypt" != "true" && "$enable_letsencrypt" != "false" ]]; then
  echo "${environment^^}_ENABLE_LETSENCRYPT must be true or false" >&2
  exit 2
fi
if [[ "$environment" == "prod" && "$enable_letsencrypt" == "true" && "$enable_duckdns" != "true" ]]; then
  echo "Production Let's Encrypt requires PROD_ENABLE_DUCKDNS=true" >&2
  exit 2
fi

duckdns_subdomain=
letsencrypt_email=
if [[ "$environment" == "prod" && "$enable_letsencrypt" == "true" ]]; then
  duckdns_subdomain=$(require_setting PROD_DUCKDNS_SUBDOMAIN)
  letsencrypt_email=$(require_setting PROD_LETSENCRYPT_EMAIL)
fi

mkdir -p "$(dirname "$deployment_file")"
{
  printf '%s\n' '# Generated by scripts/sync_github_environment.sh. Do not add secrets.'
  printf 'AWS_DEPLOY_ROLE_ARN=%s\n' "$role_arn"
  printf 'ECR_REPOSITORY_URL=%s\n' "$ecr_repository_url"
  printf 'TF_STATE_BUCKET=%s\n' "$state_bucket"
  printf 'TF_STATE_KMS_KEY_ID=%s\n' "$state_kms_key_id"
  printf 'ALARM_EMAIL=%s\n' "$alarm_email"
  printf 'ENABLE_DUCKDNS=%s\n' "$enable_duckdns"
  printf 'ENABLE_LETSENCRYPT=%s\n' "$enable_letsencrypt"
  if [[ -n "$duckdns_subdomain" ]]; then
    printf 'DUCKDNS_SUBDOMAIN=%s\n' "$duckdns_subdomain"
    printf 'LETSENCRYPT_EMAIL=%s\n' "$letsencrypt_email"
  fi
} >"$deployment_file"

# Create the protected GitHub deployment environment through the GitHub REST
# API, then mirror non-secret values to environment variables for visibility.
gh api --method PUT "repos/${repository}/environments/${environment}" >/dev/null

while IFS= read -r line; do
  [[ -z "$line" || "$line" == \#* ]] && continue
  key=${line%%=*}
  value=${line#*=}
  gh variable set "$key" --env "$environment" --repo "$repository" --body "$value"
done <"$deployment_file"

if [[ "$environment" == "prod" && "$enable_letsencrypt" == "true" ]]; then
  read -r -s -p "Enter newly rotated DUCKDNS_TOKEN: " duckdns_token </dev/tty
  printf '\n' >&2
  if [[ -z "$duckdns_token" ]]; then
    echo "DUCKDNS_TOKEN is required for automated Let's Encrypt" >&2
    exit 2
  fi
  printf '%s' "$duckdns_token" | gh secret set DUCKDNS_TOKEN \
    --env "$environment" --repo "$repository"
fi

printf 'Updated %s and GitHub environment %s for %s.\n' \
  "$deployment_file" "$environment" "$repository"
